### ISSUE TITLE
Если рядом есть Dec/Inc, то и этот должен называться Dec/Inc

### ISSUE THREAD

**Issue by coursar** [Daaamir2/Ulmart#4]
https://github.com/Daaamir2/Ulmart/blob/f56a2895e69097953d898f37309f214c8d359750/src/ru/itpark/comparator/FirmComparator.java#L8

**Comment by Daaamir2** [comment]
Исправил, добавил авто тесты 9e08608557c8be9a0b0b79815cd16155658cc8bd
