### ISSUE TITLE
Почему не сравнить на equals или equalsIgnoreCase?

### ISSUE THREAD

**Issue by coursar** [Daaamir2/Ulmart#8]
https://github.com/Daaamir2/Ulmart/blob/9cf5d63cd10cd3f73262ffd1eaf4976cdb9d4194/src/main/java/ru/itpark/service/UlmartService.java#L37

**Comment by Daaamir2** [comment]
Можно и equals, но я думаю, что с помощью contains можно будет найти продукты не полностью соответствующие запросу
Например: Название фирмы в базе "Sony", а пользователь ввел "Sony Ericson", при таком случае если использовать equals поиск ничего не найдет. Или я не прав?

**Comment by coursar** [comment]
Это в строке, а вы же в списке ищете элемент. Там contains работает по-другому. Напишите авто-тест и посмотрите
